parameters:
  buildConfiguration: 'Release'
  webAppName: 'app name'
  stageName: 'Dev'
  envName: 'development'

stages:
- stage: '${{ parameters.stageName }}'
  displayName: 'Deploy to the ${{ parameters.envName }} environment'
  dependsOn: Test
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-20.04'
    environment: ${{ parameters.envName }}
    variables:
    - group: 'Release'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: AzureWebApp@1
            displayName: 'Azure App Service Deploy: website'
            inputs:
              azureSubscription: 'Resource Manager - Tailspin - Space Game'
              appName: '${{ parameters.webAppName }}'
              package: '$(Pipeline.Workspace)/drop/${{ parameters.buildConfiguration }}/*.zip'